name: Deploy to School Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Stop existing container
      run: docker stop inflation-frontend || true

    - name: Remove existing container
      run: docker rm inflation-frontend || true

    - name: Remove existing image
      run: docker rmi inflation-frontend || true

    - name: Build Docker image
      run: docker build -t inflation-frontend .

    - name: Run Docker container
      run: docker run -d --name inflation-frontend -p 1121:3000 --restart unless-stopped inflation-frontend

    - name: Show container status
      run: docker ps | grep inflation-frontend
