name: Deploy to School Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Stop existing container
      run: docker stop inflation-frontend || true

    - name: Remove existing container
      run: docker rm inflation-frontend || true

    - name: Remove existing image
      run: docker rmi inflation-frontend || true

    - name: Build Docker image
      run: docker build -t inflation-frontend .

    - name: Run Docker container
      run: docker run -d --name inflation-frontend -p 1121:3000 --restart always inflation-frontend

    - name: Wait for container to start
      run: sleep 5

    - name: Verify container is running
      run: |
        if ! docker ps | grep -q inflation-frontend; then
          echo "Container failed to start, attempting restart..."
          sleep 5
          docker start inflation-frontend
        fi

    - name: Show container status
      run: docker ps | grep inflation-frontend
